image: registry.gitlab.com/wldhx/ouinet:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build-image:
  stage: build
  tags:
    - shell
  when: manual
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest - < Dockerfile
    - docker push $CI_REGISTRY_IMAGE:latest

build:
  stage: build
  tags:
    - docker
  artifacts:
    paths:
      - build/client
      - build/injector
      - build/test/test-*
    expire_in: 6h
  cache:
    key: single
    paths:
      - build/modules/*/go-workspace
      - build/src/ouiservice/lampshade/go-workspace
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j `nproc`

unit-test:
  stage: test
  tags:
    - docker
  script:
    - export LD_LIBRARY_PATH=/usr/local/lib
    - ./build/test/test-cache                --log_level=test_suite
    - ./build/test/test-wait-condition       --log_level=test_suite
    - ./build/test/test-bittorrent           --log_level=test_suite
    - ./build/test/test-logger               --log_level=test_suite
    - ./build/test/test-http-util            --log_level=test_suite
    - ./build/test/test-persistent-lru-cache --log_level=test_suite

integration-test:
  stage: test
  tags:
    - docker
  script:
    - export LD_LIBRARY_PATH=/usr/local/lib
    - virtualenv .venv
    - . .venv/bin/activate
    - pip install twisted
    - export OUINET_BUILD_DIR=$PWD/build
    - ./scripts/run_integration_tests.sh
