image: registry.gitlab.com/equalitie/ouinet:latest

stages:
  - build-image
  - build
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build-image:
  stage: build-image
  tags:
    - shell
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull --target base -t $CI_REGISTRY_IMAGE:latest - < Dockerfile
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker build -t $CI_REGISTRY_IMAGE:android - < Dockerfile.android
    - docker push $CI_REGISTRY_IMAGE:android

build:
  stage: build
  tags:
    - docker
  artifacts:
    paths:
      - build/client
      - build/injector
      - build/lib*.so
      - build/test/test-*
    expire_in: 6h
  cache:
    key: single
    paths:
      - build/modules/*/go-workspace
      - build/src/ouiservice/lampshade/go-workspace
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make -j `nproc`

build-android:
  stage: build
  tags:
    - docker
  image: registry.gitlab.com/equalitie/ouinet:android
  script:
    - mkdir -p build.android
    - cd build.android
    - ../scripts/build-android.sh

unit-test:
  stage: test
  tags:
    - docker
  script:
    - export LD_LIBRARY_PATH=$PWD/build:/usr/local/lib
    - for test in ./build/test/test-*; do "$test" --log_level=test_suite; done

integration-test:
  stage: test
  tags:
    - docker
  script:
    - export LD_LIBRARY_PATH=/usr/local/lib:$PWD/build/gcrypt/src/gcrypt/src/.libs:$PWD/build/gpg_error/out/lib:$PWD/build/modules/asio-ipfs/ipfs_bindings:$PWD/build/src/ouiservice/lampshade/lampshade_bindings
    - export OUINET_BUILD_DIR=$PWD/build
    - ./scripts/run_integration_tests.sh
