# Environment variables:
#
#   - OUINET_VERSION: Optional version tag (default 'latest').
#   - OUINET_ROLE: Optional node role: 'injector' or 'client' (default).
#
# Usage example for client (with default environment file):
#
#     $ echo COMPOSE_PROJECT_NAME=ouinet-client >> .env  # optional
#     $ echo OUINET_ROLE=client >> .env  # optional
#     $ docker-compose up
#
# To run a shell on its data volume:
#
#     $ docker-compose run --rm shell
#

version: '3'

services:
  shell:
    image: busybox
    volumes:
      - data:/var/opt/ouinet
    network_mode: none
    # This leaves the user at the right place when running a shell.
    working_dir: /var/opt/ouinet
    # The shell just exits successfully on up or start.

  node:
    image: "equalitie/ouinet:${OUINET_VERSION:-latest}"
    volumes:
      - data:/var/opt/ouinet
    # Host networking is preferred over port forwarding
    # if running on a Linux host (especially for injectors).
    # Otherwise see below.
    network_mode: host
    # If you get "connection refused" errors when
    # accessing the client's HTTP proxy at ``127.111.117.105:8080``,
    # comment the line above and uncomment the ones below
    # to enable port forwarding.
    #
    #network_mode: bridge
    #ports:
    #  - "127.7.2.1:8080:8080"  # client HTTP proxy
    #  - "7077:7077"  # injector TLS endpoint
    #
    # You will also need to modify ``listen-on-*`` options to
    # use ``0.0.0.0`` instead of ``127.7.2.1`` (see readme).
    #
    command: ["${OUINET_ROLE:-client}"]
    # The service will be restarted (also on reboot)
    # until it is manually stopped.
    restart: unless-stopped

volumes:
  data:
