version: 2

jobs:
  build:
    docker:
      - image: registry.gitlab.com/equalitie/ouinet:android

    environment:
      CMAKE_BUILD_PARALLEL_LEVEL: 3

    steps:
      - checkout

      - run:
          name: Build
          command: |
            git submodule sync --recursive
            git submodule update --recursive --init
            mkdir build
            cd build
            cmake ..
            cmake --build .

      - run:
          name: Test
          command: |
            export LD_LIBRARY_PATH=/usr/local/lib

            for test in ./build/test/test-*; do
                "$test" --log_level=test_suite
            done

            export LD_LIBRARY_PATH=/usr/local/lib:$PWD/build/gcrypt/src/gcrypt/src/.libs:$PWD/build/gpg_error/out/lib:$PWD/build/modules/asio-ipfs/ipfs_bindings:$PWD/build/src/ouiservice/lampshade/lampshade_bindings
            export OUINET_BUILD_DIR=$PWD/build
            ./scripts/run_integration_tests.sh

      - run:
          name: Build.Android
          command: |
            mkdir -p build.android
            cd build.android
            ../scripts/build-android.sh
